package com.zhao.community.mapper;

import com.zhao.community.model.Notifiction;
import com.zhao.community.model.NotifictionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface NotifictionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    long countByExample(NotifictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int deleteByExample(NotifictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int insert(Notifiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int insertSelective(Notifiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    List<Notifiction> selectByExampleWithRowbounds(NotifictionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    List<Notifiction> selectByExample(NotifictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    Notifiction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") Notifiction record, @Param("example") NotifictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int updateByExample(@Param("record") Notifiction record, @Param("example") NotifictionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int updateByPrimaryKeySelective(Notifiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifiction
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    int updateByPrimaryKey(Notifiction record);
}