package com.zhao.community.model;

import com.zhao.community.dto.NotificationDTO;

public class Notifiction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.id
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.notifier
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.reciever
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private Long reciever;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.outerId
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.type
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.gmt_create
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.status
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.notifierName
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private String notifiername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifiction.outertitle
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    private String outertitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.id
     *
     * @return the value of notifiction.id
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.id
     *
     * @param id the value for notifiction.id
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.notifier
     *
     * @return the value of notifiction.notifier
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.notifier
     *
     * @param notifier the value for notifiction.notifier
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.reciever
     *
     * @return the value of notifiction.reciever
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public Long getReciever() {
        return reciever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.reciever
     *
     * @param reciever the value for notifiction.reciever
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setReciever(Long reciever) {
        this.reciever = reciever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.outerId
     *
     * @return the value of notifiction.outerId
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.outerId
     *
     * @param outerid the value for notifiction.outerId
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.type
     *
     * @return the value of notifiction.type
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.type
     *
     * @param type the value for notifiction.type
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.gmt_create
     *
     * @return the value of notifiction.gmt_create
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.gmt_create
     *
     * @param gmtCreate the value for notifiction.gmt_create
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.status
     *
     * @return the value of notifiction.status
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.status
     *
     * @param status the value for notifiction.status
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.notifierName
     *
     * @return the value of notifiction.notifierName
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public String getNotifiername() {
        return notifiername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.notifierName
     *
     * @param notifiername the value for notifiction.notifierName
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setNotifiername(String notifiername) {
        this.notifiername = notifiername == null ? null : notifiername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifiction.outertitle
     *
     * @return the value of notifiction.outertitle
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public String getOutertitle() {
        return outertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifiction.outertitle
     *
     * @param outertitle the value for notifiction.outertitle
     *
     * @mbg.generated Mon Mar 22 19:44:33 CST 2021
     */
    public void setOutertitle(String outertitle) {
        this.outertitle = outertitle == null ? null : outertitle.trim();
    }


}